library(sas7bdat)
ac <- read.sas7bdat("~/EpiProjects/MT_copper_smelters/data/modcomp_allcause.sas7bdat")
aoc <- read.sas7bdat("~/EpiProjects/MT_copper_smelters/data/modcomp_allothercauses.sas7bdat")
rc <- read.sas7bdat("~/EpiProjects/MT_copper_smelters/data/modcomp_respcancer.sas7bdat")
lw <- read.sas7bdat("~/EpiProjects/MT_copper_smelters/data/modcomp_leavework.sas7bdat")
rw <- read.sas7bdat("~/EpiProjects/MT_copper_smelters/data/modcomp_returnwork.sas7bdat")
ex <- read.sas7bdat("~/EpiProjects/MT_copper_smelters/data/modcomp_multinomexp.sas7bdat")
head(ac)
head(aoc)
head(rc)
head(lw)
head(rw)
head(ex)